goalManager.updateGoal(0, 200)
// console.log(goalManager.getGoal(0))
// console.log(goalManager.getPercent(0))
// console.log(goalManager.getGoalComplete(0))
// goalManager.updateGoal(0, 400)
// console.log(goalManager.getGoal(0))
// console.log(goalManager.getPercent(0))
// console.log(goalManager.getGoalComplete(0))